### ISSUE TITLE
Image saving issue with plt.savefig() and cv2.imwrite()

### ISSUE THREAD

**Issue by ms3c** [TDC-Machine-Learning-AI-Club/face-blur#1]
I have tried to reproduce the script and everything works as expected but I have encountered a problem when trying to save then image to disk without displaying it 

I have tried below methods
 
```python 
cv2.imwrite('output_image.png', cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
```
The above method saved image to disk but it is not colorful

```python
plt.savefig('output_image.png', bbox_inches='tight')
```
The above method saved image to disk but it is blank

Kindly @CodeBot-del see what you can do

![output_image](https://github.com/TDC-Machine-Learning-AI-Club/face-blur/assets/37941160/2df9db56-7cc7-45bf-a2a4-3ef2caeb0f87)

**Comment by CodeBot-del** [comment]
Try to change the image color before saving it, so break this line:
`cv2.imwrite('output_image.png', cv2.cvtColor(img, cv2.COLOR_BGR2RGB))`

first change the image color separately before saving it. something like:
```
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
cv2.imwrite('output_image.png', img)

```
I hope this will work.

**Comment by ms3c** [comment]
Unfortunately it did not work

![image](https://github.com/TDC-Machine-Learning-AI-Club/face-blur/assets/37941160/10af6fca-cab4-4f70-9317-d8521666b734)

**Comment by CodeBot-del** [comment]
I see the issue... remove the 
`img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB))`

after plt.show()

It is causing the image to be back to BGR as it is already in RGB from prior preprocessing before plotting it. So after the line:
plt.show()

You should have only this line:
cv2.imwrite('output_image.png', img)

**Comment by ms3c** [comment]
It worked
